sudo: required
services:
  - docker
before_install:
  - docker build -t sangeetha/multi-container -f ./client/Dockerfile.dev ./client
script:
  - docker run sangeetha/multi-container npm test -- --coverage
after_success:
  - docker login -u="$DOCKER_ID" -p="$DOCKER_PASSWORD"

  - docker build -t multi-client ./client
  - docker build -t multi-nginx ./nginx
  - docker build -t multi-server ./server
  - docker build -t multi-worker ./worker	

  - docker images

  - docker tag multi-client $DOCKER_ID/multi-client
  - docker tag multi-nginx $DOCKER_ID/multi-nginx
  - docker tag multi-server $DOCKER_ID/multi-server
  - docker tag multi-worker $DOCKER_ID/multi-worker

  - docker push  $DOCKER_ID/multi-client
  - docker push  $DOCKER_ID/multi-nginx
  - docker push  $DOCKER_ID/multi-server
  - docker push  $DOCKER_ID/multi-worker
