sudo: required
services:
  - docker
before_install:
  - docker build -t sangeetha/multi-container -f ./client/Dockerfile.dev ./client
script:
  - docker run sangeetha/multi-container npm test -- --coverage
after_success:
  - docker build -t sangeetha/multi-client ./client
  - docker build -t sangeetha/multi-nginx ./nginx
  - docker build -t sangeetha/multi-server ./server
  - docker build -t sangeetha/multi-worker ./worker

  #Log in to the docker CLI
  #- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" -- password-stdin
  - docker login -u "$DOCKER_ID" -p "$DOCKER_PASSWORD"
  #Take those images and push to docker hub
  - docker tag $DOCKER_ID/sangeetha/multi-client
  - docker push $DOCKER_ID/sangeetha/multi-client
  - docker tag $DOCKER_ID/sangeetha/multi-nginx
  - docker push $DOCKER_ID/sangeetha/multi-nginx
  - docker tag $DOCKER_ID/sangeetha/multi-server
  - docker push $DOCKER_ID/sangeetha/multi-server
  - docker tag $DOCKER_ID/sangeetha/multi-worker
  - docker push $DOCKER_ID/sangeetha/multi-worker
  
